default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <db_name>
  username: <db_username>
  password: <<db_user_password>>

test:
  <<: *default
  database: <db_name>-test
  username: <db_username>
  password: <<db_user_password>>

production:
  <<: *default
  database: <db_name>-prod
  username: <db_username>
  password: <<db_user_password>>